# Generated by Django 5.0.2 on 2024-02-26 07:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inflearn_lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytext",
            name="board_text",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
