# Generated by Django 5.0.2 on 2024-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inflearn_lecture", "0003_alter_mytext_board_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytext",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
