# Generated by Django 5.0.2 on 2024-02-27 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inflearn_lecture", "0006_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="write",
            new_name="writer",
        ),
    ]
